apiVersion: apps/v1
kind: Deployment

metadata:
  name: login-deployment
  labels:
    app: login

spec:
  replicas: 3

  selector:
    matchLabels:
      app: login

  template:
    metadata:
      labels:
        app: login

    spec:
      imagePullSecrets:
        - name: login-secret

      containers:
        - name: login
          image: 531728396484.dkr.ecr.ap-south-1.amazonaws.com/lms-login:1
          ports:
            - containerPort: 3000

          env: 
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: login-secret-new
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: login-secret-new
                   key: DB_PASSWORD