apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    app: login
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: login
      image: 531728396484.dkr.ecr.ap-south-1.amazonaws.com/lms-login:1
      ports:
        - containerPort: 3000