apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester-role
  namespace: lms-uat

rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

#kubectl get role -n lms-dev 
#kubectl auth can-i get pods --as=developer -n lms-dev
#